# pepipost
#
# This file was automatically generated by APIMATIC v2.0 (
# https://apimatic.io ).

# CohesityManagementSdk
module Pepipost
  # All configuration including auth info and base URI for the API access
  # are configured in this class.
  class Configuration
    # Set the array parameter serialization method.
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    @array_serialization = 'indexed'

    # An enum for SDK environments.
    class Environment
      ENVIRONMENT = [PRODUCTION = 0].freeze
    end

    # An enum for API servers.
    class Server
      SERVER = [SERVER1 = 0, PEPI_1 = 1].freeze
    end

    # The environment in which the SDK is running.
    @environment = Environment::PRODUCTION

    # Your Pepipost API Key. You will find the api key in the Pepipost application in Integrations.
    @api_key = 'SGVsbG8gd2VsY29tZSB0byBQRVB'

    # All the environments the SDK can run in.
    @environments = {
      Environment::PRODUCTION => {
        Server::SERVER1 => 'http://apiuk-lb3.falconide.com/v5/mail',
        Server::PEPI_1 => 'https://api.pepipost.com/v5/mail'
      }
    }

    # Generates the appropriate base URI for the environment and the server.
    # @param [Configuration::Server] The server enum for which the base URI is
    # required.
    # @return [String] The base URI.
    def self.get_base_uri(server = Server::SERVER1)
      environments[environment][server].clone
    end

    # The attribute accessors for public properties.
    class << self
      attr_accessor :array_serialization
      attr_accessor :environment
      attr_accessor :environments
      attr_accessor :api_key
    end
  end
end
